apiVersion: apps/v1
kind: Deployment
metadata:
  name: as13-app
spec:
  selector:
    matchLabels:
      app: myapp1
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      imagePullSecrets:
        - name: ecr-secret   # 👈 ADD THIS
      containers:
      - name: as13-cont
        image: 949185033669.dkr.ecr.us-east-1.amazonaws.com/demo-app:50
        ports:
        - containerPort: 3000

