apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: leaderboard
        image: 949185033669.dkr.ecr.us-east-1.amazonaws.com/demo-app:58
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
spec:
  type: NodePort
  selector:
    app: leaderboard
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30008
